apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: service-requirements.io
spec:
  group: io.io
  scope: Cluster
  names:
    plural: service-requirements
    singular: service-requirement
    kind: ServiceRequirement
    shortNames:
    - sr
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                service:
                  type: object
                  properties:
                    deploymentName:
                      type: string
                    namespace:
                      type: string
                requirements:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      kind:
                        type: string