apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: service-dependencies-operator
  name: service-dependecies-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-dependencies-operator-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default "service-dependencies-operator"}}
  namespace: {{ .Release.Namespace }}
