# permissions for end users to view servicedependencies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: service-dependencies-operator
  name: servicedependency-viewer-role
rules:
- apiGroups:
  - io.io.com
  resources:
  - servicedependencies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - io.io.com
  resources:
  - servicedependencies/status
  verbs:
  - get
