apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: service-dependencies-operator
  name: {{ .Values.serviceAccount.name | default "service-dependencies-operator"}}
  namespace: {{ .Release.Namespace }}
