---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - io.io.com
  resources:
  - servicedependencies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - io.io.com
  resources:
  - servicedependencies/finalizers
  verbs:
  - update
- apiGroups:
  - io.io.com
  resources:
  - servicedependencies/status
  verbs:
  - get
  - patch
  - update
